### ISSUE TITLE
Missing answer in question

### ISSUE THREAD

**Issue by hgrampa** [denisnadey/netwhat#1]
## When checked in Russian, the question below is missing the strikethrough option.

Which of the following propositions is not true?
1.    UDP is faster, simpler and more efficient than TCP
2.    UDP only has the basic error control mechanism
3.    UDP is a datagram oriented protocol
4.    ~~UDP does not support broadcasting~~

**Comment by denisnadey** [comment]
I will fix this. Maybe.... in a few million years.
